"""Added Student model

Revision ID: 278429b2cf71
Revises: a9fe3d63b749
Create Date: 2024-02-03 11:38:09.976539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278429b2cf71'
down_revision: Union[str, None] = 'a9fe3d63b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(length=55), nullable=True),
                    sa.Column('grade', sa.Integer(), nullable=True),
                    sa.Column('birthday', sa.DateTime(), nullable=True),
                    sa.Column('enrolled_date', sa.DateTime(), nullable=True),
                    sa.CheckConstraint('grade BETWEEN 1 AND 12',
                                       name='grade_between_1_and_12'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email', name='unique_email')
                    )
    op.create_index(op.f('ix_students_name'),
                    'students', ['name'], unique=False)
    # ### end Alembi
    # c commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
